project:
  type: website

website:
  title: "Shuler Hopkins"
  navbar:
    title: "Shuler Hopkins"
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false